export async function runAutoTests(checkInput) {
  const prompts = [

    "hello ai mera assignment hai kal ai",
    "ai mera assignment friday ko hai",
    "ai mera presentation sunday ko hai",
    "ai mera parso assignment hai",
    "parso",
    "day after tommorow",
    "day after tomorrow",
    "parso tommorow",
    "parso",
    "ai mera monday ko assignment hai",
    "ai mera tuesday ko assignment hai",
    "ai mera wednesday ko assignment hai",
    "ai mera thursday ko assignment hai",
    "ai mera friday ko assignment hai",
    "ai mera satruday ko assignment hai",
    "ai mera saturday ko assignment hai ai",
    "ai mera sunday ko assignment hai ai",
    "mera is sunday ko assignment hai ai",
    "mera next sunday ko assignment hai ai",
    "ai mera kal quiz hai",
    "ai mera parso quiz hai",
    "mera quiz day after tomorrow hai",
    "ai mera Monday ko quiz hai",
    "mera Tuesday ko quiz hai",
    "mera quiz chhoot gaya",
    "quiz mein marks kam aaye",
    "quiz ka result kab aayega",
    "urdu: ai mera quiz hai kal subah",
    "urdu: mera parso quiz hai dopahar ko",
    "assignment ki deadline kal hai",
    "assignment file corrupt ho gayi",
    "assignment mein plagiarism aa gaya",
    "mere assignment kuch pages missing hain",
    "assignment ka format kya hai",
    "urdu: mera assignment kal tak submit karna hai",
    "urdu: assignment parso hai lekin main beemar hun",
    "urdu: assignment group project hai ek member ne kuch nahi kiya",
    "final exam kal hai",
    "final exam parso hai",
    "final exam day after tomorrow hai",
    "final exam Monday ko hai",
    "final exam online hoga ya offline",
    "final exam mein kya syllabus ayega",
    "final exam mein passing marks kitne hain",
    "urdu: final exam kal hai aur mene abhi start kiya hai",
    "urdu: final exam parso hai mujhe fever hai",
    "mid exam kal hai",
    "mid exam parso hai",
    "mid exam mein calculator allowed hai?",
    "mid exam ka center kahan hai",
    "mid exam postpone ho sakta hai?",
    "mid exam mein cheat sheet allowed hai?",
    "presentation kal hai",
    "presentation parso hai",
    "presentation day after tomorrow hai",
    "presentation Monday ko hai",
    "presentation ki slides kahan upload karun",
    "presentation ke liye dress code kya hai",
    "presentation group mein hai ek member absent hai",
    "presentation record ho rahi hai kya",

    "urdu: presentation parso hai laptop kharab ho gaya",
    "quiz attempt karte waqt page refresh ho gaya",
    "mere answers save nahi hue quiz mein",
    "assignment duplicate submission ho gaya",
    "ai mera kal quiz hai aur parso assignment deadline hai dono manage kaise karun",
    "ai mera same day quiz bhi hai aur presentation bhi hai",
    "kal mera final exam hai",
    "parso mera presentation hai",
    "ai mera friday ko quiz hai",
    "day after tomorrow mera quiz hai",
    "agale hafte Tuesday ko final exam hai",

  // QUIZ
  "ai mera monday ko quiz hai",
  "ai mera tuesday ko quiz hai",
  "ai mera wednesday ko quiz hai",
  "ai mera thursday ko quiz hai",
  "ai mera friday ko quiz hai",
  "ai mera saturday ko quiz hai",
  "ai mera sunday ko quiz hai",
  "mera monday morning quiz hai",
  "mera tuesday evening quiz hai",
  "mera friday afternoon quiz hai",
  "kal mera quiz hai",
  "parso mera quiz hai",
  "day after tomorrow mera quiz hai",
  "urdu: mera monday ko quiz hai subah",
  "urdu: mera friday ko quiz hai shaam ko",
  "urdu: mera parso quiz hai",
  "urdu: mera kal quiz hai",
  "ai mera quiz monday ko hai",
  "ai mera quiz friday ko hai",
  "ai mera quiz kal subah hai",
  "ai mera quiz parso raat ko hai",
  "quiz attempt karte waqt page refresh ho gaya",
  "mere answers save nahi hue quiz mein",
  "quiz portal open nahi ho raha",
  "quiz reschedule ho gaya",
  "quiz mein calculator allowed hai?",
  "quiz online hoga ya onsite?",
  "quiz ka syllabus kya hai?",

  // ASSIGNMENT
  "ai mera monday ko assignment hai",
  "ai mera tuesday ko assignment hai",
  "ai mera wednesday ko assignment hai",
  "ai mera thursday ko assignment hai",
  "ai mera friday ko assignment hai",
  "ai mera saturday ko assignment hai",
  "ai mera sunday ko assignment hai",
  "mera sunday night assignment submission hai",
  "kal mera assignment hai",
  "parso mera assignment hai",
  "day after tomorrow assignment deadline hai",
  "urdu: mera monday ko assignment hai",
  "urdu: mera friday ko assignment hai shaam ko",
  "urdu: mera kal assignment submit karna hai",
  "urdu: mera parso assignment hai",
  "ai mera assignment friday ko hai",
  "ai mera assignment kal hai",
  "ai mera assignment parso dopahar ko hai",
  "assignment duplicate submission ho gaya",
  "assignment upload nahi ho rahi",
  "assignment file corrupt ho gayi",
  "assignment late submit hui",
  "assignment ka format kya hai?",
  "assignment pdf mein submit karni hai?",
  "assignment ki deadline extend hui?",

  // PRESENTATION
  "ai mera monday ko presentation hai",
  "ai mera tuesday ko presentation hai",
  "ai mera wednesday ko presentation hai",
  "ai mera thursday ko presentation hai",
  "ai mera friday ko presentation hai",
  "ai mera saturday ko presentation hai",
  "ai mera sunday ko presentation hai",
  "mera tuesday evening presentation hai",
  "kal mera presentation hai",
  "parso mera presentation hai",
  "day after tomorrow mera presentation hai",
  "urdu: mera monday ko presentation hai",
  "urdu: mera friday ko presentation hai dopahar mein",
  "urdu: mera kal presentation hai",
  "urdu: mera parso presentation hai",
  "ai mera presentation sunday ko hai",
  "ai mera presentation kal shaam ko hai",
  "ai mera presentation parso hai",
  "presentation group mein hai ek member absent hai",
  "presentation ki slides delete ho gayi",
  "presentation record ho rahi hai kya",
  "presentation ka projector kaam nahi kar raha",
  "presentation ke liye dress code kya hai",
  "presentation ki slides kahan upload karun",
  "presentation online hogi ya physical",

  // FINAL EXAM
  "ai mera monday ko final exam hai",
  "ai mera tuesday ko final exam hai",
  "ai mera wednesday ko final exam hai",
  "ai mera thursday ko final exam hai",
  "ai mera friday ko final exam hai",
  "ai mera saturday ko final exam hai",
  "ai mera sunday ko final exam hai",
  "kal mera final exam hai",
  "parso mera final exam hai",
  "day after tomorrow mera final exam hai",
  "agale monday mera final exam hai",
  "agale tuesday mera final exam hai",
  "agale wednesday mera final exam hai",
  "agale thursday mera final exam hai",
  "agale friday mera final exam hai",
  "urdu: mera monday ko final exam hai",
  "urdu: mera friday ko final exam hai",
  "urdu: mera kal final exam hai",
  "urdu: mera parso final exam hai",
  "ai mera final exam friday ko hai",
  "ai mera final exam kal subah hai",
  "ai mera final exam parso raat ko hai",
  "final exam postpone ho gaya",
  "final exam center change ho gaya",
  "final exam admit card nahi mil raha",
  "final exam online hoga kya",
  "final exam mein calculator allowed hai",
  "final exam ka syllabus kya hai",
  "final exam kitne baje start hoga",

  // MID EXAM
  "ai mera monday ko mid exam hai",
  "ai mera tuesday ko mid exam hai",
  "ai mera wednesday ko mid exam hai",
  "ai mera thursday ko mid exam hai",
  "ai mera friday ko mid exam hai",
  "ai mera saturday ko mid exam hai",
  "ai mera sunday ko mid exam hai",
  "kal mera mid exam hai",
  "parso mera mid exam hai",
  "day after tomorrow mera mid exam hai",
  "agale monday mera mid exam hai",
  "agale tuesday mera mid exam hai",
  "agale wednesday mera mid exam hai",
  "agale thursday mera mid exam hai",
  "agale friday mera mid exam hai",
  "urdu: mera monday ko mid exam hai",
  "urdu: mera friday ko mid exam hai",
  "urdu: mera kal mid exam hai",
  "urdu: mera parso mid exam hai",
  "ai mera mid exam friday ko hai",
  "ai mera mid exam kal subah hai",
  "ai mera mid exam parso raat ko hai",
  "mid exam postpone ho gaya",
  "mid exam ka room change ho gaya",
  "mid exam portal crash ho gaya",
  "mid exam miss ho gaya",
  "mid exam mein cheat sheet allowed hai",
  "mid exam ka syllabus kya hai",
  "mid exam ka center kahan hai",
    "ai mera day after tomorrow dopahar ko presentation hai",
     "agale thursday mera final exam hai",
    "agale friday mera mid exam hai",
    "urdu: mera monday ko quiz hai subah",
    "urdu: mera tuesday ko assignment hai shaam ko",
    "urdu: mera wednesday ko presentation hai dopahar mein",
    "urdu: mera thursday ko final exam hai",
    "urdu: mera friday ko mid exam hai",
    "urdu: mera parso quiz hai aur notes missing hain",
    "urdu: mera day after tomorrow presentation hai",
    "urdu: mera kal assignment submit karna hai",
    "urdu: mera parso mid exam hai",
    "ai mera kal subah quiz hai",
    "ai mera kal shaam ko presentation hai",
    "ai mera parso dopahar ko assignment hai",
    "ai mera day after tomorrow raat ko final exam preparation session hai",
    "ai mera monday ko quiz hai aur tuesday ko assignment hai",
    "ai mera friday ko final exam hai aur sunday ko presentation hai",
    "ai mera kal quiz hai aur kal hi assignment bhi submit karna hai",
    "ai mera quiz hai wednesday ko",
    "mera monday morning quiz hai",
    "mera tuesday evening presentation hai",
    "mera friday afternoon final exam hai",
    "mera sunday night assignment submission hai",
    "kal subah mera quiz hai",
    "kal dopahar mera presentation hai",
    "parso subah mera assignment hai",
    "parso raat mera final exam preparation hai",
    "ai mera quiz monday ko hai",
  ];

  for (const prompt of prompts) {
    console.log("\n🧪 TEST:", prompt);
    await checkInput(prompt);
  }

  console.log("\n✅ All tests finished");
}